version: '2'
services:
    appspringangularjs-app:
        image: appspringangularjs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://appspringangularjs-mysql:3306/appspringangularjs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    appspringangularjs-mysql:
        extends:
            file: mysql.yml
            service: appspringangularjs-mysql
